export const CUSTOMER_SIGNIN_REQUEST = "CUSTOMER_SIGNIN_REQUEST";
export const CUSTOMER_SIGNIN_SUCCESS = "CUSTOMER_SIGNIN_SUCCESS";
export const CUSTOMER_SIGNIN_FAIL = "CUSTOMER_SIGNIN_FAIL";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";

export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";

export const CUSTOMER_VERIFIED_REQUEST = "CUSTOMER_VERIFIED_REQUEST";
export const CUSTOMER_VERIFIED_SUCCESS = "CUSTOMER_VERIFIED_SUCCESS";
export const CUSTOMER_VERIFIED_FAIL = "CUSTOMER_VERIFIED_FAIL";

export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
