export const PROVIDER_SIGNIN_REQUEST = "PROVIDER_SIGNIN_REQUEST";
export const PROVIDER_SIGNIN_SUCCESS = "PROVIDER_SIGNIN_SUCCESS";
export const PROVIDER_SIGNIN_FAIL = "PROVIDER_SIGNIN_FAIL";

export const PROVIDER_UPDATE_REQUEST = "PROVIDER_UPDATE_REQUEST";
export const PROVIDER_UPDATE_SUCCESS = "PROVIDER_UPDATE_SUCCESS";
export const PROVIDER_UPDATE_FAIL = "PROVIDER_UPDATE_FAIL";

export const PROVIDER_REGISTER_REQUEST = "PROVIDER_REGISTER_REQUEST";
export const PROVIDER_REGISTER_SUCCESS = "PROVIDER_REGISTER_SUCCESS";
export const PROVIDER_REGISTER_FAIL = "PROVIDER_REGISTER_FAIL";

export const PROVIDER_LOGOUT = "PROVIDER_LOGOUT";
